baseurl = "http://andydyer.org/"
languageCode = "en-us"
# title = "Andy Dyer"
theme = "hyde-y"
MetaDataFormat = "toml"
disqusShortname = "andydyerorg"
copyright = "© 2017 Copyright Andy Dyer"
canonifyURLs = true
relativeURLs = false

[author]
  name = "Andy Dyer"

[params]
  description = "Android & React Native developer. Conference Speaker. Beer & coffee snob. Berliner in training."

  # theme specific
  sidebar = "left"
  brand = "Andy Dyer"
  topline = "Android & React Native developer. Conference Speaker. Beer & coffee snob. Berliner in training."
  github = "abdyer"
  twitter = "dammitandy"
  linkedin = "abdyer"
  googleplus = "AndrewDyer"
  googleAnalytics = "UA-48421946-1"
  highlight = "monokai_sublime"

[permalinks]
  post = "/blog/:year/:month/:day/:title/"
