baseurl = "http://andydyer.org/"
languageCode = "en-us"
# title = "Andy Dyer"
theme = "hyde-y"
MetaDataFormat = "toml"
disqusShortname = "andydyerorg"
copyright = "© 2015 Copyright Andy Dyer"
canonifyurls = true

[author]
  name = "Andy Dyer"

[params]
  description = "Android developer. Beer & coffee snob. Cultivator of beard. Ich lerne Deutsch."

  # theme specific
  sidebar = "left"
  brand = "Andy Dyer"
  topline = "Android developer. Beer & coffee snob. Cultivator of beard. Aspiring Berliner. Ich lerne Deutsch."
  github = "abdyer"
  twitter = "dammitandy"
  linkedin = "abdyer"
  googleplus = "AndrewDyer"
  googleAnalytics = "UA-48421946-1"
  highlight = "monokai_sublime"

[permalinks]
  post = "/blog/:year/:month/:day/:title/"
