baseURL = "https://andydyer.org/"
languageCode = "en-us"
title = "Andy Dyer"
theme = "hyde-hyde"
canonifyURLs = true
relativeURLs = false
googleAnalytics = "G-PEEF2LV798"

[author]
  name = "Andy Dyer"
  
[markup.goldmark.renderer]
  unsafe= true

[permalinks]
  post = "/blog/:year/:month/:day/:title/"

[Menus]
  main = [
      {Weight = 0, Name = "Android", URL = "/categories/android"},
      {Weight = 1, Name = "Speaking", URL = "/categories/speaking"},
      {Weight = 2, Name = "Bands I've Seen Live", URL = "/blog/2009/04/19/bands-ive-seen-live"},
  ]

[params]
  description = "Staff Platform Engineer at Ibotta, editor at ProAndroidDev"
  themeColor = "theme-base-0g"
  
[params.social]
  linkedin = "abdyer"
  github = "abdyer"
  gravatar = "abdyer@gmail.com"
  mastodon = "https://mastodon.social/@andydyer"