baseurl = "http://andydyer.org"
languageCode = "en-us"
title = "Andy Dyer"
theme = "material-design"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
# disqusShortname = "Your Disqus Name" # optional
copyright = "© 2015 Copyright Andy Dyer"
canonifyurls = true

[params]
  description = "Android developer. Beer & coffee snob. Cultivator of beard. Ich lerne Deutsch."
  twitter = "dammitandy" # optional
  github = "abdyer" # optional
  # facebook = "Your facebook Name" # optional
  gplus = "AndrewDyer" # optional
  linkedin = "abdyer" # optional
  # headerCover = "images/headerCover.png" # optional
  # footerCover = "images/footerCover.png" # optional
  googleAnalyticsUserID = "UA-48421946-1" # optional

[permalinks]
  post = "/blog/:year/:month/:day/:title/" # optional
