baseURL = "https://andydyer.org/"
languageCode = "en-us"
title = "Andy Dyer!"
theme = "hyde-hyde"
canonifyURLs = true
relativeURLs = false
googleAnalytics = "UA-48421946-1"

[author]
  name = "Andy Dyer"
  
[markup.goldmark.renderer]
  unsafe= true

[permalinks]
  post = "/blog/:year/:month/:day/:title/"

[Menus]
  main = [
      {Weight = 0, Name = "Android", URL = "/categories/android"},
      {Weight = 1, Name = "Speaking", URL = "/categories/speaking"},
      {Weight = 2, Name = "Bands I've Seen Live", URL = "/blog/2009/04/19/bands-ive-seen-live"},
  ]

[params]
  description = "Senior Android Engineer <a href='https://twitter.com/zalandotech'>@ZalandoTech</a>, editor <a href='https://twitter.com/proandroiddev'>@ProAndroidDev</a>, occasional conference speaker."
  themeColor = "theme-base-0g"
  
[params.social]
  twitter = "dammitandy"
  linkedin = "abdyer"
  github = "abdyer"
  gravatar = "abdyer@gmail.com"